.gitignore, tumi-mundo/src/lib/styles/style.css
Added the background gradient and font sizings to the root of our style.css.
=> STYLE: Add root in CSS

README.MD
=> ADD: readme changes

tumi-mundo/src/routes/+page.svelte, tumi-mundo/static/lib/styles/style.css
I started adding the basic styling, like for headings and the body's background, for the "Testing" page that serves as a homepage for our feature. Would love some feedback! ♡ (including a handy css comment system we could perhaps use?)
=> STYLE: Start adding content from prototype (home/start page)

tumi-mundo/src/routes/test/+page.svelte, tumi-mundo/static/lib/scripts/index.js
Added a new route and a script. Cannot link script to test/+page.svelte and getting errors nobody else has.
=> ADD: New route and script

tumi-mundo/src/app.html, tumi-mundo/src/routes/+page.svelte, tumi-mundo/static/lib/styles/style.css
Finished some basic styling for the homepage :)
=> STYLE/ADD: Testing overview page style / privacy claim

tumi-mundo/src/routes/customization/+page.svelte, tumi-mundo/src/routes/test/+page.svelte, tumi-mundo/static/lib/styles/style.css
Start of new pre-test customization page is here! Including css variable name fix according to feedback.
=> ADD/STYLE: New customization page, edit CSS variable names

README.MD
Added an intro and table of contents to the readme.
=> README: Add intro and fix styling

tumi-mundo/static/lib/scripts/index.js
We're adding all our logic inside the components, so an external file is no longer necessary.
=> ADD: Removed scripts folder since JS will be inline.

tumi-mundo/src/routes/attentiontest/+page.svelte
It's a bit flickery, but it works! (Slightly yassified also)
=> FEAT: Test-file for attention test logs baby's attention

tumi-mundo/src/routes/+page.svelte, tumi-mundo/src/routes/customization/+page.svelte
Homepage links to customization, which links to test, which will later link to statistics.
=> ADD: Link different pages

tumi-mundo/package.json, tumi-mundo/src/app.html, tumi-mundo/src/routes/+page.svelte, tumi-mundo/src/routes/customization/+page.svelte, tumi-mundo/src/routes/statistics/+page.svelte, tumi-mundo/static/lib/styles/style.css, tumi-mundo/vite.config.js
Added styling from @briannededeugd and Live Share configuration to make sure that live server sharing works with Vite
=> ADD: customization styling and Live Share config

tumi-mundo/nodemon.json, tumi-mundo/package.json
as noted here: issue https://github.com/briannededeugd/tumimundo/issues/31
=> FIX: nodemon configuration

tumi-mundo/src/routes/attentiontest/+page.svelte
Added a progress bar with the subtlety the client asked for :)
=> FEAT: Progress bar with high frequency audio

tumi-mundo/src/routes/attentiontest/+page.svelte, tumi-mundo/static/lib/styles/style.css
Check your baby...... also fixed the attention test body margin issue in a way that's a little bit ugly but works!
=> FEAT: Check your baby before the test

tumi-mundo/vercel.json
Added the config and will test it to deploy on Vercel
=> ADD: Vercel deployment configuration

tumi-mundo/package-lock.json, tumi-mundo/package.json, tumi-mundo/src/components/LineChart.svelte, tumi-mundo/src/routes/statistics/+page.svelte
D3 package installed and some startup steps done. I got some help from @briannededeugd Thankss :)
=> starting with d3 - line graph

tumi-mundo/src/components/LineChart.svelte, tumi-mundo/src/routes/statistics/+page.svelte
I forget to move the code in the component, so this is the new version of statistics page
=> FEAT: Statistics with d3 (better version)

tumi-mundo/src/routes/attentiontest/+page.svelte, tumi-mundo/static/lib/styles/style.css
Fixed the progress bar causing it to overflow outside the body. Responsiveness beginning from 900px is turned off because of interference. This needs to be fixed later with a **different approach**.
=> FIX: Progress bar causing blank spaces in body

tumi-mundo/static/lib/styles/style.css
Code's more compact and grows organically with the viewport.
=> STYLE/FIX: Accordion and modules grow until breakpoint

tumi-mundo/src/components/LineChart.svelte
thanks to @rosemulazada it is working, just little improvements should come
=> ADD/FIX: Line chart work with 5 data like 4

tumi-mundo/src/routes/attentiontest/+page.svelte, tumi-mundo/src/routes/stores.js
Users can now toggle the motion on- and off inside of the test. (Thanks @yelunl for fixing the functionality with the store's boolean!)
=> FEAT: Toggle motion in attention test
